name: page_view_dot_indicator
description: A simple and animated page view indicator in the form of dots, which you can customise color, size, space and duration.
version: 2.2.0
homepage: https://github.com/douglasiacovelli/page_view_dot_indicator
repository: https://github.com/douglasiacovelli/page_view_dot_indicator

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2

flutter:
